export type Language = 'zh' | 'en';
export type Range = '1-10' | '1-20' | '1-30' | '1-50' | '1-100' | '1-200' | '1-500';
export type Mode = 'number-bonds' | 'vertical-add' | 'vertical-sub' | 'vertical-mixed' | 'make-ten' | 'break-ten' | 'flat-ten' | 'horizontal-add' | 'horizontal-sub' | 'horizontal-mixed' | 'horizontal-chain-add' | 'horizontal-chain-sub' | 'horizontal-chain-mixed' | 'horizontal-fill-add' | 'horizontal-fill-sub' | 'horizontal-fill-mixed';
export type RegroupOption = 'mixed' | 'none' | 'only';
export type LowerOperandDigits = 'mixed' | 'one' | 'two';

export type HorizontalFillProblem = {
  id: number;
  type: 'horizontal-fill';
  num1: number;
  num2: number;
  result: number;
  operator: '+' | '-';
  blankPosition: 1 | 2;
};

export type Problem =
  | { id: number; type: 'bond'; top: number | string; left: number | string; right: number | string; isBlank?: boolean }
  | { id: number; type: 'arithmetic'; num1: number; num2: number; operator: '+' | '-' }
  | { id: number; type: 'arithmetic-chain'; operands: [number, number, number]; operators: ['+' | '-', '+' | '-'] }
  | { id: number; type: 'method'; num1: number; num2: number; operator: '+' | '-'; method: 'make-ten' | 'break-ten' | 'flat-ten' }
  | HorizontalFillProblem;

export const pdfFileNames: Record<Language, Record<Mode, string>> = {
  zh: {
    'number-bonds': '数字组合.pdf',
    'vertical-add': '竖排加法.pdf',
    'vertical-sub': '竖排减法.pdf',
    'vertical-mixed': '竖排混合.pdf',
    'horizontal-add': '横排加法.pdf',
    'horizontal-sub': '横排减法.pdf',
    'horizontal-mixed': '横排混合.pdf',
    'horizontal-chain-add': '连续加法.pdf',
    'horizontal-chain-sub': '连续减法.pdf',
    'horizontal-chain-mixed': '连续加减混合.pdf',
    'horizontal-fill-add': '横式填空加法.pdf',
    'horizontal-fill-sub': '横式填空减法.pdf',
    'horizontal-fill-mixed': '横式填空加减混合.pdf',
    'make-ten': '凑十法.pdf',
    'break-ten': '破十法.pdf',
    'flat-ten': '平十法.pdf',
  },
  en: {
    'number-bonds': 'number-bonds.pdf',
    'vertical-add': 'vertical-addition.pdf',
    'vertical-sub': 'vertical-subtraction.pdf',
    'vertical-mixed': 'vertical-arithmetic.pdf',
    'horizontal-add': 'horizontal-addition.pdf',
    'horizontal-sub': 'horizontal-subtraction.pdf',
    'horizontal-mixed': 'horizontal-arithmetic.pdf',
    'horizontal-chain-add': 'chained-addition.pdf',
    'horizontal-chain-sub': 'chained-subtraction.pdf',
    'horizontal-chain-mixed': 'chained-mixed-arithmetic.pdf',
    'horizontal-fill-add': 'horizontal-fill-addition.pdf',
    'horizontal-fill-sub': 'horizontal-fill-subtraction.pdf',
    'horizontal-fill-mixed': 'horizontal-fill-mixed.pdf',
    'make-ten': 'make-ten.pdf',
    'break-ten': 'break-ten.pdf',
    'flat-ten': 'flat-ten.pdf',
  },
};

export const translations = {
  zh: {
    settings: '参数配置',
    preview: '打印预览',
    worksheetTitle: '习题定制',
    mode: '题型',
    range: '练习区间',
    regroup: '进退位',
    lowerOperandDigits: '下方数位数',
    makeTenLeft: '左加数',
    hideTen: '隐藏“10”辅助数字',
    hideBondParts: '隐藏底部分解数字',
    regenerate: '重新生成题目',
    viewPreview: '查看打印预览',
    print: '直接打印',
    downloadPdf: '下载 PDF',
    mobileRegenerate: '换一批',
    mobilePrint: '打印',
    mobileDownload: '下载',
    date: '日期',
    name: '姓名',
    score: '得分',
    modes: {
      'number-bonds': '数字组合',
      'vertical-add': '竖排加法',
      'vertical-sub': '竖排减法',
      'vertical-mixed': '竖排混合',
      'horizontal-add': '横排加法',
      'horizontal-sub': '横排减法',
      'horizontal-mixed': '横排混合',
      'horizontal-chain-add': '连续加法',
      'horizontal-chain-sub': '连续减法',
      'horizontal-chain-mixed': '连续加减混合',
      'horizontal-fill-add': '加法',
      'horizontal-fill-sub': '减法',
      'horizontal-fill-mixed': '加减混合',
      'make-ten': '凑十法',
      'break-ten': '破十法',
      'flat-ten': '平十法',
    },
    regroupOptions: {
      mixed: '混合',
      none: '不进退位',
      only: '需进退位',
    },
    lowerOperandDigitOptions: {
      mixed: '一位数与两位数混合',
      one: '一位数',
      two: '两位数',
    },
    makeTenLeftOptions: {
      mixed: '随机',
      '9': '9',
      '8': '8',
      '7': '7',
      '6': '6',
      '5': '5',
    },
    printTitles: {
      'number-bonds': '数字组合',
      'vertical-add': '竖排加法',
      'vertical-sub': '竖排减法',
      'vertical-mixed': '竖排混合',
      'horizontal-add': '横排加法',
      'horizontal-sub': '横排减法',
      'horizontal-mixed': '横排混合',
      'horizontal-chain-add': '连续加法',
      'horizontal-chain-sub': '连续减法',
      'horizontal-chain-mixed': '连续加减混合',
      'horizontal-fill-add': '横式填空（加法）',
      'horizontal-fill-sub': '横式填空（减法）',
      'horizontal-fill-mixed': '横式填空（加减混合）',
      'make-ten': '凑十法',
      'break-ten': '破十法',
      'flat-ten': '平十法',
    },
    bondNumber: '目标数字',
    bondUseTypeStudy: '学习卡片模式',
    blankTemplate: '空白模板模式',
    selectProblemType: '请选择习题类型',
    selectProblemTypeHint: '从左侧选择一种练习，习题预览将在这里显示。',
    sectionMethod: '方法训练',
    sectionArithmetic: '算式练习',
    sectionFill: '填空练习',
    sectionConfig: '题目配置',
    limitedProblemCount: (actual: number, requested: number) =>
      `当前配置最多可生成 ${actual} 道不重复题，少于计划的 ${requested} 道。`,
  },
  en: {
    settings: 'Settings',
    preview: 'Preview',
    worksheetTitle: 'Worksheet Settings',
    mode: 'Mode',
    range: 'Practice Band',
    regroup: 'Regrouping',
    lowerOperandDigits: 'Lower Operand Digits',
    makeTenLeft: 'Left Addend',
    hideTen: 'Hide helper "10"',
    hideBondParts: 'Hide bottom parts',
    regenerate: 'Regenerate Problems',
    viewPreview: 'View Preview',
    print: 'Print',
    downloadPdf: 'Download PDF',
    mobileRegenerate: 'New Set',
    mobilePrint: 'Print',
    mobileDownload: 'Download',
    date: 'Date',
    name: 'Name',
    score: 'Score',
    modes: {
      'number-bonds': 'Number Bonds',
      'vertical-add': 'Vertical Addition',
      'vertical-sub': 'Vertical Subtraction',
      'vertical-mixed': 'Vertical Mixed',
      'horizontal-add': 'Horizontal Addition',
      'horizontal-sub': 'Horizontal Subtraction',
      'horizontal-mixed': 'Horizontal Mixed',
      'horizontal-chain-add': 'Chained Addition',
      'horizontal-chain-sub': 'Chained Subtraction',
      'horizontal-chain-mixed': 'Chained Mixed',
      'horizontal-fill-add': 'Addition',
      'horizontal-fill-sub': 'Subtraction',
      'horizontal-fill-mixed': 'Mixed',
      'make-ten': 'Make-Ten Method',
      'break-ten': 'Break-Ten Method',
      'flat-ten': 'Flat-Ten Method',
    },
    regroupOptions: {
      mixed: 'Mixed',
      none: 'Without Regrouping',
      only: 'With Regrouping',
    },
    lowerOperandDigitOptions: {
      mixed: 'Mixed One- and Two-Digit',
      one: 'One Digit',
      two: 'Two Digits',
    },
    makeTenLeftOptions: {
      mixed: 'Mixed',
      '9': '9',
      '8': '8',
      '7': '7',
      '6': '6',
      '5': '5',
    },
    printTitles: {
      'number-bonds': 'Number Bonds',
      'vertical-add': 'Vertical Addition',
      'vertical-sub': 'Vertical Subtraction',
      'vertical-mixed': 'Vertical Arithmetic',
      'horizontal-add': 'Horizontal Addition',
      'horizontal-sub': 'Horizontal Subtraction',
      'horizontal-mixed': 'Horizontal Arithmetic',
      'horizontal-chain-add': 'Chained Addition',
      'horizontal-chain-sub': 'Chained Subtraction',
      'horizontal-chain-mixed': 'Chained Mixed Arithmetic',
      'horizontal-fill-add': 'Horizontal Fill (Addition)',
      'horizontal-fill-sub': 'Horizontal Fill (Subtraction)',
      'horizontal-fill-mixed': 'Horizontal Fill (Mixed)',
      'make-ten': 'Make-Ten Method',
      'break-ten': 'Break-Ten Method',
      'flat-ten': 'Flat-Ten Method',
    },
    bondNumber: 'Target Number',
    bondUseTypeStudy: 'Learning Card Mode',
    blankTemplate: 'Blank Template Mode',
    selectProblemType: 'Select a problem type',
    selectProblemTypeHint: 'Choose an exercise from the left to see its worksheet preview here.',
    sectionMethod: 'Method Training',
    sectionArithmetic: 'Arithmetic Practice',
    sectionFill: 'Fill-in-the-Blank',
    sectionConfig: 'Problem Settings',
    limitedProblemCount: (actual: number, requested: number) =>
      `This configuration has ${actual} unique problems, fewer than the requested ${requested}.`,
  },
};
