export type Language = 'zh' | 'en';
export type Range = '1-10' | '11-20' | '21-30' | '10-50' | '10-100' | '20-regroup';
export type Mode = 'number-bonds' | 'vertical-add' | 'vertical-sub' | 'vertical-mixed' | 'make-ten' | 'break-ten' | 'flat-ten' | 'horizontal-add' | 'horizontal-sub' | 'horizontal-mixed';
export type RegroupOption = 'mixed' | 'none' | 'only';

export type Problem = 
  | { id: number; type: 'bond'; top: number | string; left: number | string; right: number | string; isBlank?: boolean }
  | { id: number; type: 'arithmetic'; num1: number; num2: number; operator: '+' | '-' }
  | { id: number; type: 'method'; num1: number; num2: number; operator: '+' | '-'; method: 'make-ten' | 'break-ten' | 'flat-ten' };

export const pdfFileNames: Record<Language, Record<Mode, string>> = {
  zh: {
    'number-bonds': '数字组合.pdf',
    'vertical-add': '竖排加法.pdf',
    'vertical-sub': '竖排减法.pdf',
    'vertical-mixed': '竖排混合.pdf',
    'horizontal-add': '横排加法.pdf',
    'horizontal-sub': '横排减法.pdf',
    'horizontal-mixed': '横排混合.pdf',
    'make-ten': '凑十法.pdf',
    'break-ten': '破十法.pdf',
    'flat-ten': '平十法.pdf',
  },
  en: {
    'number-bonds': 'number-bonds.pdf',
    'vertical-add': 'vertical-addition.pdf',
    'vertical-sub': 'vertical-subtraction.pdf',
    'vertical-mixed': 'vertical-arithmetic.pdf',
    'horizontal-add': 'horizontal-addition.pdf',
    'horizontal-sub': 'horizontal-subtraction.pdf',
    'horizontal-mixed': 'horizontal-arithmetic.pdf',
    'make-ten': 'make-ten.pdf',
    'break-ten': 'break-ten.pdf',
    'flat-ten': 'flat-ten.pdf',
  },
};

export const translations = {
  zh: {
    settings: '参数配置',
    preview: '打印预览',
    worksheetTitle: '习题定制',
    mode: '题型',
    range: '难度',
    regroup: '进退位',
    makeTenLeft: '左加数',
    hideTen: '隐藏“10”辅助数字',
    hideBondParts: '隐藏底部分解数字',
    regenerate: '重新生成题目',
    viewPreview: '查看打印预览',
    print: '直接打印',
    downloadPdf: '下载 PDF',
    mobileRegenerate: '换一批',
    mobilePrint: '打印',
    mobileDownload: '下载',
    date: '日期',
    name: '姓名',
    score: '得分',
    modes: {
      'number-bonds': '数字组合',
      'vertical-add': '竖排加法',
      'vertical-sub': '竖排减法',
      'vertical-mixed': '竖排混合',
      'horizontal-add': '横排加法',
      'horizontal-sub': '横排减法',
      'horizontal-mixed': '横排混合',
      'make-ten': '凑十法',
      'break-ten': '破十法',
      'flat-ten': '平十法',
    },
    regroupOptions: {
      mixed: '混合',
      none: '无进/退位',
      only: '进/退位',
    },
    makeTenLeftOptions: {
      mixed: '随机',
      '9': '9',
      '8': '8',
      '7': '7',
      '6': '6',
      '5': '5',
    },
    printTitles: {
      'number-bonds': '数字组合',
      'vertical-add': '竖排加法',
      'vertical-sub': '竖排减法',
      'vertical-mixed': '竖排混合',
      'horizontal-add': '横排加法',
      'horizontal-sub': '横排减法',
      'horizontal-mixed': '横排混合',
      'make-ten': '凑十法',
      'break-ten': '破十法',
      'flat-ten': '平十法',
    },
    bondNumber: '目标数字',
    bondUseTypeStudy: '学习卡片模式',
    blankTemplate: '空白模板模式',
  },
  en: {
    settings: 'Settings',
    preview: 'Preview',
    worksheetTitle: 'Worksheet Settings',
    mode: 'Mode',
    range: 'Range',
    regroup: 'Regroup',
    makeTenLeft: 'Left Addend',
    hideTen: 'Hide helper "10"',
    hideBondParts: 'Hide bottom parts',
    regenerate: 'Regenerate Problems',
    viewPreview: 'View Preview',
    print: 'Print',
    downloadPdf: 'Download PDF',
    mobileRegenerate: 'New Set',
    mobilePrint: 'Print',
    mobileDownload: 'Download',
    date: 'Date',
    name: 'Name',
    score: 'Score',
    modes: {
      'number-bonds': 'Number Bonds',
      'vertical-add': 'Vertical Addition',
      'vertical-sub': 'Vertical Subtraction',
      'vertical-mixed': 'Vertical Mixed',
      'horizontal-add': 'Horizontal Addition',
      'horizontal-sub': 'Horizontal Subtraction',
      'horizontal-mixed': 'Horizontal Mixed',
      'make-ten': 'Make-Ten Method',
      'break-ten': 'Break-Ten Method',
      'flat-ten': 'Flat-Ten Method',
    },
    regroupOptions: {
      mixed: 'Mixed',
      none: 'No Regroup',
      only: 'Regroup Only',
    },
    makeTenLeftOptions: {
      mixed: 'Mixed',
      '9': '9',
      '8': '8',
      '7': '7',
      '6': '6',
      '5': '5',
    },
    printTitles: {
      'number-bonds': 'Number Bonds',
      'vertical-add': 'Vertical Addition',
      'vertical-sub': 'Vertical Subtraction',
      'vertical-mixed': 'Vertical Arithmetic',
      'horizontal-add': 'Horizontal Addition',
      'horizontal-sub': 'Horizontal Subtraction',
      'horizontal-mixed': 'Horizontal Arithmetic',
      'make-ten': 'Make-Ten Method',
      'break-ten': 'Break-Ten Method',
      'flat-ten': 'Flat-Ten Method',
    },
    bondNumber: 'Target Number',
    bondUseTypeStudy: 'Learning Card Mode',
    blankTemplate: 'Blank Template Mode',
  },
};
